#!/usr/bin/env bash
##Trap the loop with SIGTERM

x=1
while [ $x -gt 0 ]
 do
      echo "To infinity and beyond"
      sleep 2
 done
trap 
      echo "I am invincible!!!"
      pkill -f "4-to_infinity_and_beyond" SIGTERM
