#!/usr/bin/env bash
##This script displays numbers 1-20; 4 then bad luck from China, 9 then bad luck from Japan, 17 then bad luck from Italy

n=1
while [ $n -le 20 ]
do
      echo "$n" 
      
      case $n in
         
         4)
           echo "bad luck from China"
           ;;
         9)
           echo "bad luck from Japan"
           ;;
         17) 
           echo "bad luck from Italy"
           ;;

 esac 
((n++)) 

done         
